import json
import sys
from datetime import datetime, timezone

def generate_codeql_report(codescanning_count):
    """Generate a markdown report for CodeQL security issues"""
    
    current_time = datetime.now(timezone.utc)
    
    print("# CodeQL Security Issues Report\n")
    print(f"This report lists the currently open CodeQL security vulnerabilities in this repository.")
    print(f"The data is collected from GitHub's Code Scanning API and updated with each push or merge to main.\n")
    print(f"**Generated on:** {current_time.strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
    
    print("## Summary\n")
    print("| Alert Type | Count |")
    print("|------------|-------|")
    print(f"| CodeQL Alerts | {codescanning_count} |")
    
    if codescanning_count > 0:
        print("## Analysis\n")
        print(f"### CodeQL Alerts: {codescanning_count}")
        print("CodeQL alerts indicate potential security vulnerabilities found in the source code.")
        print("These should be reviewed and addressed promptly to maintain code security.\n")

    else:
        print("## Status: No Open CodeQL Issues")
        print("\nNo open CodeQL security issues were found in this repository.")
    
    print("---")
    print("*This report is automatically generated by the CI pipeline.*")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: generate_codeql_report.py <codescanning_count>", file=sys.stderr)
        sys.exit(1)
    
    try:
        codescanning_count = int(sys.argv[1])
    except ValueError:
        print("Error: CodeQL count must be a valid integer", file=sys.stderr)
        sys.exit(1)
    
    generate_codeql_report(codescanning_count)